version: "3.9"

services:
  insaf-api:
    build: .
    container_name: insaf-recommender
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
